<?php
/**
 * Chart post type.
 *
 * @package WebAula\Charts
 */

namespace WebAula\Charts;

defined( 'ABSPATH' ) || exit;

/**
 * Registers the `wa_chart` post type and its admin list behaviour.
 */
final class Post_Type {

	public const SLUG             = 'wa_chart';
	public const ROLES            = array( 'administrator', 'editor' );
	public const DUPLICATE_ACTION = 'wa_charts_duplicate';
	public const COPY_HANDLE      = 'wa-charts-copy';

	/**
	 * Hooks.
	 *
	 * @return void
	 */
	public static function register_hooks(): void {
		add_action( 'init', array( self::class, 'register' ) );
		add_filter( 'manage_' . self::SLUG . '_posts_columns', array( self::class, 'columns' ) );
		add_action( 'manage_' . self::SLUG . '_posts_custom_column', array( self::class, 'column_content' ), 10, 2 );
		add_filter( 'post_row_actions', array( self::class, 'row_actions' ), 10, 2 );
		add_action( 'admin_post_' . self::DUPLICATE_ACTION, array( self::class, 'handle_duplicate' ) );
		add_action( 'admin_enqueue_scripts', array( self::class, 'enqueue_list_assets' ) );
	}

	/**
	 * Registers the post type, its meta and the copy script.
	 *
	 * @return void
	 */
	public static function register(): void {
		register_post_type(
			self::SLUG,
			array(
				'labels'                => array(
					'name'          => __( 'Charts', 'wa-charts' ),
					'singular_name' => __( 'Chart', 'wa-charts' ),
					'menu_name'     => __( 'Charts', 'wa-charts' ),
					'all_items'     => __( 'All charts', 'wa-charts' ),
					'add_new_item'  => __( 'Add new chart', 'wa-charts' ),
					'edit_item'     => __( 'Edit chart', 'wa-charts' ),
					'new_item'      => __( 'New chart', 'wa-charts' ),
					'search_items'  => __( 'Search charts', 'wa-charts' ),
					'not_found'     => __( 'No charts found.', 'wa-charts' ),
				),
				'public'                => false,
				'publicly_queryable'    => false,
				'exclude_from_search'   => true,
				'show_ui'               => true,
				'show_in_menu'          => true,
				'show_in_nav_menus'     => false,
				'show_in_rest'          => true,
				'rest_base'             => 'wa_chart',
				'rest_controller_class' => Rest_Controller::class,
				'has_archive'           => false,
				'rewrite'               => false,
				'query_var'             => false,
				'menu_icon'             => 'dashicons-chart-pie',
				'menu_position'         => 25,
				'supports'              => array( 'title', 'revisions' ),
				'capability_type'       => array( 'wa_chart', 'wa_charts' ),
				'map_meta_cap'          => true,
			)
		);

		register_post_meta(
			self::SLUG,
			Chart_Data::META_KEY,
			array(
				'type'              => 'string',
				'single'            => true,
				'show_in_rest'      => false,
				'revisions_enabled' => true,
				'auth_callback'     => static fn( $allowed, $meta_key, $post_id ) => current_user_can( 'edit_post', (int) $post_id ),
			)
		);

		wp_register_script( self::COPY_HANDLE, WA_CHARTS_URL . 'assets/admin/copy.js', array(), WA_CHARTS_VERSION, true );
	}

	/**
	 * Primitive capabilities generated by `capability_type`.
	 *
	 * @return string[]
	 */
	public static function capabilities(): array {
		return array(
			'edit_wa_charts',
			'edit_others_wa_charts',
			'edit_private_wa_charts',
			'edit_published_wa_charts',
			'publish_wa_charts',
			'read_private_wa_charts',
			'delete_wa_charts',
			'delete_others_wa_charts',
			'delete_private_wa_charts',
			'delete_published_wa_charts',
		);
	}

	/**
	 * Gives administrators and editors all chart capabilities.
	 *
	 * @return void
	 */
	public static function grant_caps(): void {
		foreach ( self::ROLES as $role_name ) {
			$role = get_role( $role_name );
			if ( ! $role ) {
				continue;
			}
			foreach ( self::capabilities() as $cap ) {
				if ( ! $role->has_cap( $cap ) ) {
					$role->add_cap( $cap );
				}
			}
		}
	}

	/**
	 * List table columns.
	 *
	 * @param array $columns Core columns.
	 * @return array
	 */
	public static function columns( array $columns ): array {
		return array(
			'cb'           => $columns['cb'] ?? '<input type="checkbox" />',
			'title'        => $columns['title'] ?? __( 'Title', 'wa-charts' ),
			'wa_type'      => __( 'Type', 'wa-charts' ),
			'wa_shortcode' => __( 'Shortcode', 'wa-charts' ),
			'wa_usage'     => __( 'Used on', 'wa-charts' ),
			'wa_modified'  => __( 'Modified', 'wa-charts' ),
		);
	}

	/**
	 * Custom column output.
	 *
	 * @param string $column  Column key.
	 * @param int    $post_id Chart ID.
	 * @return void
	 */
	public static function column_content( string $column, int $post_id ): void {
		switch ( $column ) {
			case 'wa_type':
				$type = Chart_Types::get( Chart_Data::get( $post_id )['type'] );
				printf(
					'<span class="dashicons dashicons-%1$s" aria-hidden="true"></span> %2$s',
					esc_attr( $type['icon'] ),
					esc_html( $type['label'] )
				);
				break;
			case 'wa_shortcode':
				echo self::shortcode_field( $post_id ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped in shortcode_field().
				break;
			case 'wa_usage':
				$count = count( Usage::find( $post_id ) );
				if ( ! $count ) {
					echo '—';
					break;
				}
				$label = $count >= 50 ? number_format_i18n( $count ) . '+' : number_format_i18n( $count );
				$link  = get_edit_post_link( $post_id );
				echo $link
					? '<a href="' . esc_url( $link . '#wa-charts-usage' ) . '">' . esc_html( $label ) . '</a>'
					: esc_html( $label );
				break;
			case 'wa_modified':
				echo esc_html( (string) get_the_modified_date( '', $post_id ) );
				break;
		}
	}

	/**
	 * Shortcode text for a chart.
	 *
	 * @param int $post_id Chart ID.
	 * @return string
	 */
	public static function shortcode( int $post_id ): string {
		return sprintf( '[wa_chart id="%d"]', $post_id );
	}

	/**
	 * Shortcode with a copy button (escaped HTML).
	 *
	 * @param int $post_id Chart ID.
	 * @return string
	 */
	public static function shortcode_field( int $post_id ): string {
		$code = self::shortcode( $post_id );
		return sprintf(
			'<span class="wa-charts-shortcode"><code>%1$s</code> <button type="button" class="button button-small" data-wa-copy="%2$s" data-wa-copied="%3$s">%4$s</button></span>',
			esc_html( $code ),
			esc_attr( $code ),
			esc_attr__( 'Copied!', 'wa-charts' ),
			esc_html__( 'Copy', 'wa-charts' )
		);
	}

	/**
	 * Adds the Duplicate row action.
	 *
	 * @param array    $actions Row actions.
	 * @param \WP_Post $post    Post.
	 * @return array
	 */
	public static function row_actions( array $actions, \WP_Post $post ): array {
		if ( self::SLUG !== $post->post_type || ! current_user_can( 'edit_wa_charts' ) ) {
			return $actions;
		}
		$url                     = wp_nonce_url(
			add_query_arg(
				array(
					'action' => self::DUPLICATE_ACTION,
					'post'   => $post->ID,
				),
				admin_url( 'admin-post.php' )
			),
			self::DUPLICATE_ACTION . '_' . $post->ID
		);
		$actions['wa_duplicate'] = sprintf( '<a href="%s">%s</a>', esc_url( $url ), esc_html__( 'Duplicate', 'wa-charts' ) );
		return $actions;
	}

	/**
	 * Handles the Duplicate action.
	 *
	 * @return void
	 */
	public static function handle_duplicate(): void {
		$post_id = isset( $_GET['post'] ) ? absint( $_GET['post'] ) : 0; // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Verified on the next line.
		check_admin_referer( self::DUPLICATE_ACTION . '_' . $post_id );
		if ( ! current_user_can( 'edit_post', $post_id ) || ! current_user_can( 'edit_wa_charts' ) ) {
			wp_die( esc_html__( 'You are not allowed to duplicate this chart.', 'wa-charts' ), 403 );
		}
		$new_id = self::duplicate( $post_id );
		if ( is_wp_error( $new_id ) ) {
			wp_die( esc_html( $new_id->get_error_message() ) );
		}
		wp_safe_redirect( (string) get_edit_post_link( $new_id, 'raw' ) );
		exit;
	}

	/**
	 * Copies a chart as a draft.
	 *
	 * @param int $post_id Source chart ID.
	 * @return int|\WP_Error New chart ID.
	 */
	public static function duplicate( int $post_id ) {
		$post = get_post( $post_id );
		if ( ! $post || self::SLUG !== $post->post_type ) {
			return new \WP_Error( 'wa_charts_not_found', __( 'Chart not found.', 'wa-charts' ) );
		}
		$new_id = wp_insert_post(
			array(
				'post_type'   => self::SLUG,
				'post_status' => 'draft',
				/* translators: %s: original chart title. */
				'post_title'  => wp_slash( sprintf( __( '%s (copy)', 'wa-charts' ), $post->post_title ) ),
			),
			true
		);
		if ( is_wp_error( $new_id ) ) {
			return $new_id;
		}
		Chart_Data::save( $new_id, Chart_Data::get( $post_id ) );
		return $new_id;
	}

	/**
	 * Copy button script on the chart list screen.
	 *
	 * @param string $hook Admin page hook.
	 * @return void
	 */
	public static function enqueue_list_assets( string $hook ): void {
		$screen = get_current_screen();
		if ( 'edit.php' === $hook && $screen && self::SLUG === $screen->post_type ) {
			wp_enqueue_script( self::COPY_HANDLE );
		}
	}
}
